# Generated by Django 4.0.4 on 2022-06-28 05:33

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('contenido', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='blog')),
                ('fecha_creaciont', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
