# Generated by Django 4.0.4 on 2022-06-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='fecha_creaciont',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
